### ISSUE TITLE
How to configure the Kafka cluster id as the same across all (point to the same Zookeeper)

### ISSUE THREAD

**Issue by Kirity** [confluentinc/confluent-kubernetes-examples#223]
Hi !

I'm trying to setup the multi-region-clusters as described in [multi-region-clusters](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/hybrid/multi-region-clusters)

In the process of Kafka set up, it is given as  'Configure the Kafka cluster id as the same across all (point to the same Zookeeper)' 
 
![image](https://user-images.githubusercontent.com/15073157/226869498-6c5ddb8e-ba26-4f7a-8d71-5c38c9fc31d8.png)

How to achieve this?

**Comment by MosheBlumbergX** [comment]
It's built into the YAML, so you don't actually have to do anything, it happens when you deploy them. 

https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/hybrid/multi-region-clusters/confluent-platform/kafka/kafka-central.yaml#L28

https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/hybrid/multi-region-clusters/confluent-platform/kafka/kafka-east.yaml#L30

https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/hybrid/multi-region-clusters/confluent-platform/kafka/kafka-west.yaml#L30

**Comment by Kirity** [comment]
@MosheBlumbergX  Thank you for the quick response.
